### PR TITLE
Adds AnacondaRecipes integration test data

### PR DESCRIPTION
**Pull request by schuylermartin45**
Adds randomly selected public [AnacondaRecipes](https://github.com/AnacondaRecipes) feedstock repository recipes.

This list has been filtered for:
- Obviously test aggregate junk repos
- Feedstocks with multiple variants (i.e. `*-feedstock-1`, `*feedstcok-2`, etc...)

### CODE REVIEW

**Comment by schuylermartin45** [comment]
@jezdez 
Licensing info that I've gathered (from our offline conversation):
- AnacondaRecipes:
  - Most license files for recipes I see list 2015 as the earliest year and 2022 as the latest year
  - `aggregate`'s top-layer contains:
    ```
    Copyright (c) 2012, Anaconda, Inc.
    Copyright (c) 2015-2019, conda-forge
    ```
- Bioconda: `Copyright (c) 2015-2022 The Bioconda team` (MIT)
- conda-forge: `Copyright (c) 2015-2022, conda-forge contributors` (BSD-3-Clause)
  - This is my best guess from checking a few of the recipes and matches what was probably copied in the Anaconda Recipes files

**Comment by jezdez** [comment]
@schuylermartin45 Excellent, let's update the LICENSE file of this repo with that info, maybe per directory, e.g. `recipes_v0/anaconda_recipes_01` would contain the appropriate LICENSE information where it came from?

**Comment by schuylermartin45** [comment]
I don't see any harm in doing both, I'll get right on that

**Review by jezdez — APPROVED** [review]

**Comment by jezdez** [comment]
Nicely done, thank you!

**Pull request merged**
